### ISSUE TITLE
假人死亡后无法正常复活&销毁

### ISSUE THREAD

**Issue by HappyTigerV** [xBoyMinemc/FUCKfakePlayerPack#1]
当假人~~被玩家折磨致死~~死亡后，无法复活（即使开了立即重生），并且使用“假人销毁”命令无法正常销毁（无论是否带编号），会报错

解决办法：重进、/reload（会带走假人生成地附近的建筑）
（可能是mj的锅，也可能是个bug）

**Comment by xBoyMinemc** [comment]
感谢您的反馈，这就淦bug

HappyTigerV ***@***.***> 于2022年7月17日周日 11:28写道：

**Comment by xBoyMinemc** [comment]
1.假人的确无法复活
2.使用序号销毁理应成功，例如我测试时“假人销毁 0”
3.在1.19.0.5未复现
4.使用reload后生成地附近地形依旧正常

考虑提供更多信息或尝试复现
再次感谢您的反馈，若我有所进展将会及时完成修复

**Comment by xBoyMinemc** [comment]
请提供报错信息以帮助定位错误

**Comment by xBoyMinemc** [comment]
因为reload时并不会触发本add内的任何逻辑，所以我有些迷惑
而复活是老问题，可以实现类似效果但最终还是没有那么做
销毁的实际命令内容和报错可能会给问题带来转机

**Comment by HappyTigerV** [comment]
我的版本：
正式版1.19.10

**Comment by HappyTigerV** [comment]
> 1.假人的确无法复活
> 2.使用序号销毁理应成功，例如我测试时“假人销毁 0”
> 3.在1.19.0.5未复现
> 4.使用reload后生成地附近地形依旧正常
> 
> 考虑提供更多信息或尝试复现
> 再次感谢您的反馈，若我有所进展将会及时完成修复

使用版本：基岩版1.19.10（正式版）
（将录制视频并提交）

**Comment by HappyTigerV** [comment]
> 1.假人的确无法复活
> 2.使用序号销毁理应成功，例如我测试时“假人销毁 0”
> 3.在1.19.0.5未复现
> 4.使用reload后生成地附近地形依旧正常
> 
> 考虑提供更多信息或尝试复现
> 再次感谢您的反馈，若我有所进展将会及时完成修复

修正：
~~（我也不知道为什么测试的时候不行，现在销毁带编号可以正常使用，我是傻逼！）~~
1.确实可以销毁，我是sb
2.版本1.19.10，/reload后会重置地形，类似于生成测试结构后用/gametest clearall得到的结果

**Comment by HappyTigerV** [comment]
> > 1.假人的确无法复活
> > 2.使用序号销毁理应成功，例如我测试时“假人销毁 0”
> > 3.在1.19.0.5未复现
> > 4.使用reload后生成地附近地形依旧正常
> > 
> > 考虑提供更多信息或尝试复现
> > 再次感谢您的反馈，若我有所进展将会及时完成修复
> 
> 修正：
> ~~（我也不知道为什么测试的时候不行，现在销毁带编号可以正常使用，我是傻逼！）~~
> 1.确实可以销毁，我是sb
> 2.版本1.19.10，/reload后会重置地形，类似于生成测试结构后用/gametest clearall得到的结果

（视频总是出错，不知怎么发给你）

**Comment by xBoyMinemc** [comment]
哭笑，1.19.10.3未能触发
场景为一个死了的假人 一个活着的，/reload后正常

你所描述的我可以想象，但确实无法触发

考虑尽量不使用/reload

我使用的是最新版假人文件


服务器可以考虑使用假人插件，毕竟本模组还是太。。。（哭不出来）

**Comment by HappyTigerV** [comment]
> 哭笑，1.19.10.3未能触发
> 场景为一个死了的假人 一个活着的，/reload后正常
> 
> 你所描述的我可以想象，但确实无法触发
> 
> 考虑尽量不使用/reload
> 
> 我使用的是最新版假人文件
> 
> 
> 服务器可以考虑使用假人插件，毕竟本模组还是太。。。（哭不出来）

一般来讲确实不会用reload
那就把这个issue关了吧
就当是我脑子抽了

**Comment by HappyTigerV** [comment]
等等
要不要开个新issue
代码里有挖掘功能，但帮助列表里没有（

**Comment by xBoyMinemc** [comment]
如果官方api有所动静或我有天想干活了，会解决这些潜在炒饭的
