### ISSUE TITLE
使用1.19.50假人模组时，生物死亡后会显示死亡坐标和死亡事件

### ISSUE THREAD

**Issue by wltbal7** [xBoyMinemc/FUCKfakePlayerPack#5]
![3cbade561f46d97e](https://user-images.githubusercontent.com/121443043/209556931-4d85209c-7c4f-48ed-8892-468ac5efe84f.png)

**Comment by xBoyMinemc** [comment]
已处理
见修改后的文件
https://github.com/xBoyMinemc/FUCKfakePlayerPack/releases/tag/1.19.50
